### ISSUE TITLE
Design updates

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-doi#12]
- Need to find more relevant and suitable background image.
- Header could have less height
- Search box should be more prominent, like in geocollections portal.
- In list view, entire row should be link to detail page
- In detail view, there should be one main 'card' to include all sections. The latter may have light border but no need to stress them by shadow
- Main text font size could be slightly larger 
- SARV-DOI in header should also be link to front page

**Comment by ollehints** [comment]
In DOI detail view, the large banner (search box could be in the header toolbar row).

**Comment by enmust** [comment]
TODO: 
- Need to find more relevant and suitable background image.
- In list view, entire row should be link to detail page
- Main text font size could be slightly larger
